CREATE TABLE `dm_quanhuyen` (
	`MA_QUAN_HUYEN` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`TEN_QUAN_HUYEN` VARCHAR(250) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`MA_TINH` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`LOAI` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
