CREATE TABLE `to_do` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`id_user` INT(10) UNSIGNED NOT NULL,
	`noi_dung` LONGTEXT NULL COLLATE 'utf8_unicode_ci',
	`file` LONGTEXT NULL,
	`ngay_tao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`ngay_giao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`han_xu_ly` DATETIME NULL DEFAULT NULL,
	`ngay_hoan_thanh` DATETIME NULL DEFAULT NULL,
	`sap_xep` INT(11) NOT NULL DEFAULT '0',
	`trang_thai` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	INDEX `FK_to_do_users` (`id_user`),
	CONSTRAINT `FK_to_do_users` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=47;