CREATE TABLE `dm_xaphuong` (
	`MA_PHUONG_XA` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`TEN_PHUONG_XA` VARCHAR(250) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`LOAI` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`MA_QUAN_HUYEN` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
